### ISSUE TITLE
bsdtar not found on ubuntu 18.04

### ISSUE THREAD

**Issue by jeremymcjunkin** [rynop/abp-single-lambda-api#1]
setup.sh: line 64: bsdtar: command not found

  Error: Error downloading https://github.com/rynop/abp-single-lambda-api/archive/master.zip

jeremy@jeremy-desktop:~/clearsky/snaptab-platform-api$ bsdtar

Command 'bsdtar' not found, but can be installed with:

sudo apt install libarchive-tools

**Comment by rynop** [comment]
Please add req check to https://github.com/rynop/abp-single-lambda-api/blob/master/bin/setup.sh#L11

**Comment by rynop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [NS maps](https://trello.com/c/QfB1Zt9N/14-ns-maps)
